version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: test
    volumes:
      - postgres:/var/lib/postgresql/testdata
volumes:
  postgres:
